name: pylint & black

on: 
  push:

jobs:
  build:
    runs-on: [self-hosted, universal]
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Check format
      uses: psf/black@20.8b1
      with:
        args: ". --check"
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
